version: "3.1"

services:
  mongo:
    image: mongo:4
    restart: unless-stopped
    volumes:
      - ./data/mongo:/data/db

  bot:
    build: .
    restart: unless-stopped
    command: yarn start
    env_file: .env
    environment:
      MONGODB_URL: mongodb://mongo:27017/shipid
      DEBUG: shipid
      VIRTUAL_HOST: shipid.holodata.org
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: shipid.holodata.org
