version: "3.1"

services:
  postgres:
    image: postgres:12
    # environment:
    #   POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  bot:
    build: .
    restart: unless-stopped
    command: node .
    env_file: .env
    environment:
      NODE_ENV: production
    networks:
      - default
      - webproxy
    depends_on:
      - postgres

networks:
  webproxy:
    external: true
